"""Data loading and preprocessing pipeline for AAIRM.

Supports three data modes:
    synthetic   — generated by DemandGenerator (default, no download needed)
    m5          — M5 Forecasting Competition (Kaggle, Walmart data)
    favorita    — Corporación Favorita Grocery Sales (Kaggle)

All modes produce the same unified schema consumed by RetailEnv and baselines.
"""

from aairm.data.loader import DataLoader
from aairm.data.preprocessor import Preprocessor

__all__ = ["DataLoader", "Preprocessor"]
