"""Unified Dataset Loader.

Provides a single entry point for loading any AAIRM-supported dataset.
All modes return the same dict structure consumed by RetailEnv and baselines.

Modes:
    synthetic  — Generated by DemandGenerator (default, no download needed).
    m5         — M5 Forecasting Competition data (requires download).
    favorita   — Corporación Favorita data (requires download).

References
----------
Repo Guide Section 10.2.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Literal

import numpy as np

from aairm.utils.config import AAIRMConfig
from aairm.utils.logging import get_logger
from aairm.utils.seed import set_global_seed

logger = get_logger(__name__)

DatasetMode = Literal["synthetic", "m5", "favorita"]


class DataLoader:
    """Load and return any AAIRM dataset in the unified schema.

    Args:
        config: Top-level :class:`~aairm.utils.config.AAIRMConfig`.
        mode: Dataset to load — ``"synthetic"``, ``"m5"``, or ``"favorita"``.
        processed_dir: Directory containing preprocessed parquet files.
    """

    def __init__(
        self,
        config: AAIRMConfig,
        mode: DatasetMode = "synthetic",
        processed_dir: str | Path = "data/processed",
    ) -> None:
        self._config = config
        self._mode = mode
        self._processed_dir = Path(processed_dir)
        set_global_seed(config.simulation.seed)

    def load(self) -> dict[str, Any]:
        """Load the configured dataset.

        Returns:
            Unified schema dict:
            ``{demand_history, sku_catalog, supplier_catalog, calendar}``.

        Raises:
            ValueError: If ``mode`` is not recognised.
            FileNotFoundError: If real-world data files are missing.
        """
        logger.info("dataloader.load", mode=self._mode)

        if self._mode == "synthetic":
            return self._load_synthetic()
        elif self._mode == "m5":
            return self._load_m5()
        elif self._mode == "favorita":
            return self._load_favorita()
        else:
            raise ValueError(
                f"Unknown dataset mode '{self._mode}'. "
                "Choose from: synthetic, m5, favorita."
            )

    # ------------------------------------------------------------------
    # Private loaders
    # ------------------------------------------------------------------

    def _load_synthetic(self) -> dict[str, Any]:
        """Build synthetic data from the configured simulation parameters."""
        from aairm.simulation.sku_catalog import SKUCatalog
        from aairm.simulation.demand_generator import DemandGenerator
        from aairm.simulation.supplier_simulator import SupplierSimulator
        from aairm.data.adapters.synthetic_adapter import SyntheticAdapter

        sim_cfg = self._config.simulation
        catalog = SKUCatalog(
            n_skus=sim_cfg.n_skus,
            category_names=sim_cfg.category_names,
            seed=sim_cfg.seed,
        )
        gen = DemandGenerator(
            catalog,
            n_days=sim_cfg.simulation_horizon_days,
            seed=sim_cfg.seed,
        )
        sup = SupplierSimulator(
            catalog,
            n_suppliers_min=sim_cfg.n_suppliers_min,
            n_suppliers_max=sim_cfg.n_suppliers_max,
            seed=sim_cfg.seed,
            config=self._config,
        )
        adapter = SyntheticAdapter(catalog, gen, sup)
        data = adapter.to_unified_schema()
        logger.info(
            "dataloader.synthetic_ready",
            n_skus=len(data["sku_catalog"]),
            n_days=sim_cfg.simulation_horizon_days,
        )
        return data

    def _load_m5(self) -> dict[str, Any]:
        """Load M5 data via M5Adapter, optionally preprocessing first."""
        from aairm.data.adapters.m5_adapter import M5Adapter
        from aairm.data.preprocessor import Preprocessor

        adapter = M5Adapter("data/raw/m5")
        raw = adapter.load()

        preprocessor = Preprocessor(self._processed_dir)
        processed = preprocessor.fit_transform(
            raw["demand_history"],
            raw["sku_catalog"],
            raw["calendar"],
            dataset_name="m5",
        )
        return {**raw, **processed, "source": "m5"}

    def _load_favorita(self) -> dict[str, Any]:
        """Load Favorita data via FavoritaAdapter."""
        from aairm.data.adapters.favorita_adapter import FavoritaAdapter
        from aairm.data.preprocessor import Preprocessor

        adapter = FavoritaAdapter("data/raw/favorita")
        raw = adapter.load()

        preprocessor = Preprocessor(self._processed_dir)
        processed = preprocessor.fit_transform(
            raw["demand_history"],
            raw["sku_catalog"],
            raw["calendar"],
            dataset_name="favorita",
        )
        return {**raw, **processed, "source": "favorita"}
